spring.application.name=springpfc
spring.datasource.url=jdbc:postgresql://localhost:5432/springpfc
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=uma-chave-secreta-com-pelo-menos-32-caracteres
jwt.expiracao-ms=3600000